/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account with a password.
         *
         *     Self-service registration is a development and seeding affordance. A real
         *     deployment invites care-network members rather than letting anyone claim an
         *     actor id, so this refuses to run outside dev.
         */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/device-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Device Login
         * @description Sign in a shared family device on the person's behalf.
         */
        post: operations["device_login_v1_auth_device_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the whole refresh family. Never an error, even for a bad token.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who am I, and whose data may I reach?
         *
         *     The client builds its navigation from this rather than from a static menu,
         *     so an unauthorised surface is absent rather than greyed out (DESIGN.md B2).
         */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol Device
         * @description Enrol a shared family device for a person.
         *
         *     Only a caregiver with an active relationship to that person may do this, and
         *     the enrolment is audited: putting a new device into someone's home widens
         *     who can reach their surface, which is a scope change.
         */
        post: operations["enrol_device_v1_auth_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Observation
         * @description Record one observation and return the measurement-quality decision.
         *
         *     An observation with audibility near zero, or a language mismatch, returns
         *     `gate="insufficient_data"`: the system refuses to score it. That refusal is
         *     a measurement finding, never a cognitive one.
         */
        post: operations["submit_observation_v1_persons__person_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/companion/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Companion Turn
         * @description One governed turn.
         *
         *     This is both the text companion and the fallback for every voice path, so it
         *     carries the same guarantees either way: emergency and medication never reach
         *     a model, retrieval is firewall-scoped, and the Safety Gateway runs over the
         *     result.
         */
        post: operations["companion_turn_v1_persons__person_id__companion_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/voice/capability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Voice Capability
         * @description What voice is possible here, so the client never offers what cannot work.
         */
        get: operations["voice_capability_v1_persons__person_id__voice_capability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/voice/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Session
         * @description Mint an ephemeral realtime credential for the person's own surface.
         *
         *     The browser receives a short-lived session secret and never the API key.
         *     Instructions carry orientation only; every fact the model states must come
         *     back through `/voice/tool`, where the firewall runs.
         */
        post: operations["voice_session_v1_persons__person_id__voice_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/voice/tool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Tool
         * @description Execute one tool call the realtime model asked for.
         *
         *     This is the firewall's seat in the voice loop. The model can ask for
         *     anything; what comes back is whatever this actor is authorised to know, and
         *     an unauthorised or unknown request returns "not found" rather than an error
         *     the person would hear as a failure.
         */
        post: operations["voice_tool_v1_persons__person_id__voice_tool_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/baseline/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Baseline
         * @description Deviation of the latest observation against this person's own baseline.
         *
         *     Always the person's own history — never a population norm, and never a
         *     synthetic stand-in. A person with no observations gets
         *     `gate="insufficient_data"`, which is a truthful answer.
         */
        get: operations["get_baseline_v1_persons__person_id__baseline__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/safety/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Output
         * @description Run the Safety Gateway 10 checks against a raw text string.
         *
         *     Constructs a minimal ThreeLayerOutput (one fact + one action) with the
         *     provided text as raw_text, then runs all 10 checks. If any blocking check
         *     fails, passed=False and blocked_by names the check.
         *
         *     This is the demo endpoint for: "app refuses to say 'she has dementia'."
         */
        post: operations["check_output_v1_safety_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Person */
        post: operations["create_person_v1_identity_persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_v1_identity_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Actor */
        post: operations["create_actor_v1_identity_actors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Relationship
         * @description Bind an actor to a person with a role.
         *
         *     This is the single most privileged write in the system: it is what grants
         *     anybody access to anybody. It is a bootstrap/seed path, not a runtime one —
         *     in a real deployment a person or their primary caregiver issues an
         *     invitation, which is a Phase-2 flow.
         */
        post: operations["link_relationship_v1_identity_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/consent/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Consent */
        post: operations["grant_consent_v1_identity_consent_grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/consent/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Consent
         * @description Revocation is always available and never blocked (DESIGN.md F7).
         */
        post: operations["revoke_consent_v1_identity_consent_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/persons/{person_id}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Consent
         * @description What is shared, and with whom. The person's transparency view (E5.3).
         */
        get: operations["list_consent_v1_identity_persons__person_id__consent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pwm/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Node */
        post: operations["post_node_v1_pwm_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pwm/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Edge */
        post: operations["post_edge_v1_pwm_edges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pwm/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Fact
         * @description Attempt to read a PWM fact through the Memory Firewall.
         *
         *     `authorize` establishes the caller's role for this person from the database
         *     and raises 404 if they have none, so a stranger never reaches the firewall
         *     at all. Beyond that boundary, every attempt — allowed or denied — is audited,
         *     and the response carries the decision reason so the UI can explain *why*
         *     access was granted or refused (DESIGN.md E5.2).
         */
        post: operations["read_fact_v1_pwm_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_v1_persons__person_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/caregiver-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caregiver Card */
        get: operations["caregiver_card_v1_persons__person_id__caregiver_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alert Feedback
         * @description Record how useful an alert was.
         *
         *     The alert's own person is read first so the caller can be authorized against
         *     it — an alert id must not be a way to reach a household you have no
         *     relationship with.
         */
        post: operations["alert_feedback_v1_alerts__alert_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/projections/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Projection
         * @description The caller's own projection, and nothing else.
         *
         *     `actor` was resolved from the authenticated principal plus a care
         *     relationship read from the database. A role cannot be requested.
         */
        get: operations["my_projection_v1_persons__person_id__projections_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persons/{person_id}/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projections
         * @description All four role views of one statement, derived in a single pass.
         *
         *     Restricted to the person themself. This is their "who can see my things?"
         *     answer (DESIGN.md E5.3), not a window a caregiver gets into the clinician's
         *     record.
         */
        get: operations["projections_v1_persons__person_id__projections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed
         * @description Reset and rebuild the demo firewall scenario.
         */
        post: operations["seed_v1_demo_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/inject-decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Decline
         * @description Seed a real observation history (baseline + N days below it), run the
         *     escalation pipeline, and return the Safety-Gateway-validated caregiver card.
         *
         *     This makes the caregiver card non-synthetic: the FACT comes from persisted
         *     observations, the level from the deterministic alert-eligibility function,
         *     and the card text passes the Safety Gateway.
         */
        post: operations["inject_decline_v1_demo_inject_decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorAccount */
        ActorAccount: {
            /** Actor Id */
            actor_id: string;
            /** Display Name */
            display_name: string;
            /** Created At */
            created_at?: string | null;
        };
        /** ActorCreate */
        ActorCreate: {
            /** Actor Id */
            actor_id: string;
            /** Display Name */
            display_name: string;
        };
        /** Alert */
        Alert: {
            /** Alert Id */
            alert_id: string;
            /** Person Id */
            person_id: string;
            /** Domain */
            domain: string;
            /** Level */
            level: string;
            /** Z */
            z: number;
            /** Persistence Days */
            persistence_days: number;
            /** Reason Codes */
            reason_codes: string[];
            /** Status */
            status: string;
            /** Feedback */
            feedback: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AlertFeedback */
        AlertFeedback: {
            /** Alert Id */
            alert_id: string;
            /**
             * Feedback
             * @enum {string}
             */
            feedback: "useful" | "expected" | "not_useful";
        };
        /** BaselineResponse */
        BaselineResponse: {
            /** Person Id */
            person_id: string;
            /** Domain */
            domain: string;
            /** Z */
            z: number | null;
            /** Median */
            median: number | null;
            /** Mad */
            mad: number | null;
            /** N Quality Gated */
            n_quality_gated: number;
            /** Gate */
            gate: string;
            /** Reason */
            reason: string;
        };
        /** CardFact */
        CardFact: {
            /** Content */
            content: string;
            /** Source */
            source: string;
            /** Confidence */
            confidence: number;
        };
        /** CardHypothesis */
        CardHypothesis: {
            /** Content */
            content: string;
            /**
             * Label
             * @default This is not a diagnosis.
             */
            label: string;
        };
        /** CareRelationship */
        CareRelationship: {
            /** Actor Id */
            actor_id: string;
            /** Person Id */
            person_id: string;
            role: components["schemas"]["Role"];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** CareRelationshipCreate */
        CareRelationshipCreate: {
            /** Actor Id */
            actor_id: string;
            /** Person Id */
            person_id: string;
            role: components["schemas"]["Role"];
        };
        /**
         * CaregiverCard
         * @description A three-layer caregiver card that has passed the Safety Gateway.
         */
        CaregiverCard: {
            /** Person Id */
            person_id: string;
            /** Level */
            level: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Facts */
            facts: components["schemas"]["CardFact"][];
            hypothesis: components["schemas"]["CardHypothesis"] | null;
            /** Actions */
            actions: string[];
            /** What This Is Not */
            what_this_is_not: string;
            /** Safety Passed */
            safety_passed: boolean;
            /** Measurement Confidence */
            measurement_confidence: string;
        };
        /** CheckResultOut */
        CheckResultOut: {
            /** Check */
            check: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
            /** Obligations */
            obligations: string[];
        };
        /**
         * CompanionTurn
         * @description One governed answer, with everything needed to explain it.
         *
         *     `sources` is what powers "Why am I seeing this?" (DESIGN.md E5.2): an
         *     evidence summary, never a reasoning transcript.
         */
        CompanionTurn: {
            /** Request Id */
            request_id: string;
            /** Answer */
            answer: string;
            /** Intent */
            intent: string;
            /** Path */
            path: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["TurnSource"][];
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /**
             * Conflicting
             * @default false
             */
            conflicting: boolean;
            /**
             * Hedged
             * @default false
             */
            hedged: boolean;
            /**
             * Safety Passed
             * @default true
             */
            safety_passed: boolean;
            /** Blocked By */
            blocked_by?: string | null;
            /**
             * Lanes Run
             * @default []
             */
            lanes_run: string[];
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Prompt Version
             * @default companion/1
             */
            prompt_version: string;
            /**
             * Speakable
             * @default true
             */
            speakable: boolean;
        };
        /** ConsentGrantRequest */
        ConsentGrantRequest: {
            /** Person Id */
            person_id: string;
            grantee_role: components["schemas"]["Role"];
            category: components["schemas"]["DataCategory"];
            purpose: components["schemas"]["Purpose"];
        };
        /** ConsentGrantView */
        ConsentGrantView: {
            /** Person Id */
            person_id: string;
            grantee_role: components["schemas"]["Role"];
            category: components["schemas"]["DataCategory"];
            purpose: components["schemas"]["Purpose"];
            /** Granted */
            granted: boolean;
            /** Granted At */
            granted_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
        };
        /** ConsentList */
        ConsentList: {
            /** Person Id */
            person_id: string;
            /** Grants */
            grants?: components["schemas"]["ConsentGrantView"][];
        };
        /**
         * DataCategory
         * @description Categories of person data. Visibility rules attach to categories.
         *
         *     RAW_AV and FINANCIAL are *never collected*; they exist here only so the
         *     firewall can hard-deny and flag any request for them as a violation.
         * @enum {string}
         */
        DataCategory: "person_private_note" | "life_story_memory" | "pwm_fact" | "cognitive_state" | "routine" | "clinical_summary" | "continence" | "live_position" | "raw_av" | "financial";
        /** DeviceEnrolRequest */
        DeviceEnrolRequest: {
            /** Person Id */
            person_id: string;
            /** Device Label */
            device_label: string;
        };
        /**
         * DeviceEnrolResponse
         * @description The secret is returned exactly once and never stored in plaintext.
         */
        DeviceEnrolResponse: {
            /** Device Id */
            device_id: string;
            /** Person Id */
            person_id: string;
            /** Device Label */
            device_label: string;
            /** Device Secret */
            device_secret: string;
        };
        /**
         * DeviceLoginRequest
         * @description A shared family tablet presenting its enrolment secret.
         */
        DeviceLoginRequest: {
            /** Person Id */
            person_id: string;
            /** Device Secret */
            device_secret: string;
        };
        /**
         * EscalationLevel
         * @description The L0–L5 ladder. Some categories (live position) are only accessible
         *     during an active high escalation.
         * @enum {string}
         */
        EscalationLevel: "L0" | "L1" | "L2" | "L3" | "L4" | "L5";
        /** EvaluateResponse */
        EvaluateResponse: {
            /** Person Id */
            person_id: string;
            alert: components["schemas"]["Alert"] | null;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus an honest capability report.
         *
         *     The client renders a truthful degraded state from this rather than
         *     discovering a missing deployment through a failed call. `demo_mode` is what
         *     lets every surface label seeded data as seeded, so demo content is never
         *     mistaken for a real person's record.
         */
        Health: {
            /** Status */
            status: string;
            /** App */
            app: string;
            /** Env */
            env: string;
            /** Version */
            version: string;
            /** Demo Mode */
            demo_mode: boolean;
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
        };
        /** InjectDeclineRequest */
        InjectDeclineRequest: {
            /**
             * Days
             * @default 3
             */
            days: number;
        };
        /** InjectDeclineResponse */
        InjectDeclineResponse: {
            /** Person Id */
            person_id: string;
            /** Days */
            days: number;
            /** Baseline Points */
            baseline_points: number;
            alert: components["schemas"]["Alert"] | null;
            card: components["schemas"]["CaregiverCard"];
            /** Message */
            message: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description Who am I, and whose data may I reach? The client builds navigation from this.
         */
        MeResponse: {
            /** Actor Id */
            actor_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Subject Kind
             * @enum {string}
             */
            subject_kind: "human" | "person_device";
            /**
             * Persons
             * @default []
             */
            persons: components["schemas"]["PersonSummary"][];
        };
        /** MyProjectionResponse */
        MyProjectionResponse: {
            /** Person Id */
            person_id: string;
            /** Domain */
            domain: string;
            /** Change Kind */
            change_kind: string;
            /** Statement */
            statement: string;
            /** Reversible Causes */
            reversible_causes: string[];
            /** Open Questions */
            open_questions: string[];
            /** Measurement Confidence */
            measurement_confidence: string;
            /** Interpretation Withheld */
            interpretation_withheld: boolean;
            view: components["schemas"]["ProjectionView"];
        };
        /** ObservationRequest */
        ObservationRequest: {
            /** Domain */
            domain: string;
            /**
             * Value
             * @description Normalised performance ∈ [0,1]
             */
            value: number;
            signals?: components["schemas"]["ObservationSignalsIn"];
        };
        /** ObservationResponse */
        ObservationResponse: {
            /** Observation Id */
            observation_id: string;
            /** Person Id */
            person_id: string;
            /** Domain */
            domain: string;
            /** Q */
            q: number;
            /** Gate */
            gate: string;
            /** Language Mismatch */
            language_mismatch: boolean;
            /** Dominant Issue */
            dominant_issue: string | null;
            /** Component Scores */
            component_scores: {
                [key: string]: number;
            };
            /** Message */
            message: string;
        };
        /**
         * ObservationSignalsIn
         * @description API input for observation signals — mirrors ObservationSignals with defaults.
         */
        ObservationSignalsIn: {
            /**
             * Audibility
             * @default 1
             */
            audibility: number;
            /**
             * Visibility
             * @default 1
             */
            visibility: number;
            /**
             * Language Match
             * @default true
             */
            language_match: boolean;
            /**
             * Fatigue Factor
             * @default 1
             */
            fatigue_factor: number;
            /**
             * Was Assisted
             * @default false
             */
            was_assisted: boolean;
            /**
             * Device Ok
             * @default true
             */
            device_ok: boolean;
            /**
             * Subject Confirmed
             * @default true
             */
            subject_confirmed: boolean;
        };
        /**
         * PWMEdge
         * @description A typed relationship edge between two PWM nodes (API representation).
         */
        PWMEdge: {
            /** Edge Id */
            edge_id: string;
            /** Subject Node Id */
            subject_node_id: string;
            /** Predicate */
            predicate: string;
            /** Object Node Id */
            object_node_id: string;
            provenance: components["schemas"]["ProvenanceEnvelope"];
        };
        /**
         * PWMNode
         * @description A node in the Personal World Model graph (API representation).
         */
        PWMNode: {
            /** Node Id */
            node_id: string;
            /** Person Id */
            person_id: string;
            /** Node Type */
            node_type: string;
            /**
             * Temporal Partition
             * @enum {string}
             */
            temporal_partition: "past" | "present" | "future";
            /** Label */
            label: string;
            provenance: components["schemas"]["ProvenanceEnvelope"];
        };
        /** Person */
        Person: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Preferred Language */
            preferred_language: string;
            /** Language Tier */
            language_tier: string;
            /** Cultural Context */
            cultural_context: string;
            /** Self Actor Id */
            self_actor_id: string;
            /** Created At */
            created_at?: string | null;
        };
        /** PersonCreate */
        PersonCreate: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Preferred Language
             * @default as
             */
            preferred_language: string;
            /**
             * Language Tier
             * @default A
             */
            language_tier: string;
            /**
             * Cultural Context
             * @default assamese_v1
             */
            cultural_context: string;
        };
        /**
         * PersonSummary
         * @description One person this actor may act for, with the role they hold for them.
         */
        PersonSummary: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Preferred Language */
            preferred_language: string;
            /** Language Tier */
            language_tier: string;
        };
        /**
         * ProjectionView
         * @description What one role receives — or, precisely, what it did not.
         */
        ProjectionView: {
            /** Role */
            role: string;
            /** Delivery Class */
            delivery_class: string;
            /** Interrupts */
            interrupts: boolean;
            /** Suppressed */
            suppressed: boolean;
            /** Delivery Reasons */
            delivery_reasons: string[];
            /** Headline */
            headline?: string | null;
            /**
             * Facts
             * @default []
             */
            facts: string[];
            /** Hypothesis */
            hypothesis?: string | null;
            /**
             * Actions
             * @default []
             */
            actions: string[];
            /** Measurement Confidence */
            measurement_confidence?: string | null;
            /** Escalation Level */
            escalation_level?: string | null;
            /**
             * Claim Ids
             * @default []
             */
            claim_ids: string[];
            /** Withheld At */
            withheld_at?: string | null;
            /**
             * Withheld Reasons
             * @default []
             */
            withheld_reasons: string[];
        };
        /** ProjectionsResponse */
        ProjectionsResponse: {
            /** Person Id */
            person_id: string;
            /** Domain */
            domain: string;
            /** Change Kind */
            change_kind: string;
            /** Statement */
            statement: string;
            /** Reversible Causes */
            reversible_causes: string[];
            /** Open Questions */
            open_questions: string[];
            /** Measurement Confidence */
            measurement_confidence: string;
            /** Interpretation Withheld */
            interpretation_withheld: boolean;
            /** Views */
            views: components["schemas"]["ProjectionView"][];
        };
        /**
         * ProvenanceEnvelope
         * @description The provenance envelope carried on every PWM fact.
         *
         *     This is the JSONB blob stored in pwm_nodes.provenance and pwm_edges.provenance.
         *     It is also the structure required by the Studio grounding validator via
         *     app.studio.validators.ResolvedFact.
         */
        ProvenanceEnvelope: {
            /** Fact Id */
            fact_id: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Object */
            object: string;
            /**
             * Value
             * @default {}
             */
            value: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @default {}
             */
            source: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Last Verified */
            last_verified?: string | null;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** @default unverified */
            verification_status: components["schemas"]["VerificationStatus"];
            /**
             * Visibility
             * @default []
             */
            visibility: string[];
            /**
             * Clinical Relevance
             * @default false
             */
            clinical_relevance: boolean;
            /** Audit Ref */
            audit_ref?: string | null;
        };
        /**
         * Purpose
         * @description Purpose limitation — every access declares why. A purpose not permitted
         *     for the (role, category) is denied even if the role could otherwise read.
         * @enum {string}
         */
        Purpose: "self_access" | "onboarding" | "personalisation" | "care_coordination" | "safety_response" | "clinical_review" | "research";
        /**
         * PwmReadRequest
         * @description A fact read request.
         *
         *     There is deliberately **no `actor_id` field**. It used to be here, and it
         *     meant the Memory Firewall was evaluating an identity the caller had simply
         *     typed. The actor now comes from the bearer token plus a care relationship
         *     read from the database, and nothing in this body can influence it.
         */
        PwmReadRequest: {
            /** Person Id */
            person_id: string;
            /** Fact Id */
            fact_id: string;
            /** @default personalisation */
            purpose: components["schemas"]["Purpose"];
            /** @default L0 */
            escalation: components["schemas"]["EscalationLevel"];
        };
        /** PwmReadResponse */
        PwmReadResponse: {
            /** Found */
            found: boolean;
            /** Allowed */
            allowed: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Obligations */
            obligations: string[];
            fact?: components["schemas"]["ProvenanceEnvelope"] | null;
            /** Explanation */
            explanation: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description Account creation. Dev/seed only — real deployment invites, not self-serves.
         */
        RegisterRequest: {
            /** Actor Id */
            actor_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Role
         * @description An actor's role **relative to a specific person (the data subject)**.
         *
         *     The same human may hold different roles for different persons. Roles are
         *     never global; they are always evaluated against a subject.
         * @enum {string}
         */
        Role: "person" | "primary_caregiver" | "secondary_caregiver" | "chw" | "clinician" | "admin" | "system";
        /** SafetyCheckRequest */
        SafetyCheckRequest: {
            /** Text */
            text: string;
            /** @default primary_caregiver */
            role_target: components["schemas"]["Role"];
        };
        /** SafetyCheckResponse */
        SafetyCheckResponse: {
            /** Passed */
            passed: boolean;
            /** Blocked By */
            blocked_by: string | null;
            /** Crisis Number */
            crisis_number: string | null;
            /** Obligations */
            obligations: string[];
            /** Check Results */
            check_results: components["schemas"]["CheckResultOut"][];
            /** Explanation */
            explanation: string;
        };
        /** SeedResponse */
        SeedResponse: {
            /** Person Id */
            person_id: string;
            /** Fact Id */
            fact_id: string;
            /** Actors */
            actors: {
                [key: string]: string;
            };
            /** Scenarios */
            scenarios: components["schemas"]["SeedScenario"][];
            /** Message */
            message: string;
        };
        /** SeedScenario */
        SeedScenario: {
            /** Label */
            label: string;
            /** Actor Id */
            actor_id: string;
            /** Purpose */
            purpose: string;
            /** Expected */
            expected: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ToolCallRequest */
        ToolCallRequest: {
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ToolCallResponse */
        ToolCallResponse: {
            /** Tool Name */
            tool_name: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** TurnRequest */
        TurnRequest: {
            /** Message */
            message: string;
            /**
             * Speakable
             * @default true
             */
            speakable: boolean;
        };
        /**
         * TurnSource
         * @description Where one statement in the answer came from.
         */
        TurnSource: {
            /** Fact Id */
            fact_id: string;
            /** Source Type */
            source_type: string;
            /** Verified */
            verified: boolean;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "verified" | "reported" | "unverified";
        /**
         * VoiceCapability
         * @description What voice this deployment and this person can actually have.
         */
        VoiceCapability: {
            /** Provider */
            provider: string;
            /** Realtime Available */
            realtime_available: boolean;
            /** Language */
            language: string;
            /** Language Tier */
            language_tier: string;
            /** Speech Input Supported */
            speech_input_supported: boolean;
            /** Speech Output Supported */
            speech_output_supported: boolean;
            /** Fallback */
            fallback: string;
            /** Note */
            note: string;
        };
        /** VoiceSessionResponse */
        VoiceSessionResponse: {
            /** Provider */
            provider: string;
            /** Session Id */
            session_id: string;
            /** Client Secret */
            client_secret: string;
            /** Expires At */
            expires_at: number;
            /** Model */
            model: string;
            /** Voice */
            voice: string;
            /** Webrtc Url */
            webrtc_url: string;
            /** Tools */
            tools: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_login_v1_auth_device_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    enrol_device_v1_auth_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceEnrolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceEnrolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_observation_v1_persons__person_id__observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    companion_turn_v1_persons__person_id__companion_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanionTurn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_capability_v1_persons__person_id__voice_capability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceCapability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_session_v1_persons__person_id__voice_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_tool_v1_persons__person_id__voice_tool_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_baseline_v1_persons__person_id__baseline__domain__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_output_v1_safety_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_person_v1_identity_persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_v1_identity_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_actor_v1_identity_actors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_relationship_v1_identity_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareRelationshipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareRelationship"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_consent_v1_identity_consent_grant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentGrantView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_v1_identity_consent_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentGrantView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consent_v1_identity_persons__person_id__consent_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_node_v1_pwm_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PWMNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PWMNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_edge_v1_pwm_edges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PWMEdge"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PWMEdge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_fact_v1_pwm_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PwmReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PwmReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_v1_persons__person_id__evaluate_post: {
        parameters: {
            query?: {
                domain?: string;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    caregiver_card_v1_persons__person_id__caregiver_card_get: {
        parameters: {
            query?: {
                domain?: string;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_feedback_v1_alerts__alert_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_projection_v1_persons__person_id__projections_me_get: {
        parameters: {
            query?: {
                domain?: string;
                sleep_disrupted?: boolean;
                hearing_aid_unused?: boolean;
                infection_signs?: boolean;
                constipation_reported?: boolean;
                into_shared_family_view?: boolean;
                care_relevant?: boolean;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projections_v1_persons__person_id__projections_get: {
        parameters: {
            query?: {
                domain?: string;
                sleep_disrupted?: boolean;
                hearing_aid_unused?: boolean;
                infection_signs?: boolean;
                constipation_reported?: boolean;
                into_shared_family_view?: boolean;
                care_relevant?: boolean;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_v1_demo_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
        };
    };
    inject_decline_v1_demo_inject_decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InjectDeclineRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectDeclineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
