import { GameExperienceSpecification } from "../types";

// ── 1. Static Deterministic Game Spec (Level A) ──────────────────────────────
export const staticTimelineSpecLevelA: GameExperienceSpecification = {
  id: "spec_timeline_static_level_a",
  person_id: "person:generic_elder",
  template_key: "my_life_timeline",
  template_version: "1.2.0",
  version: "1.2.0",
  generation_mode: "static_level_a",
  title: "Life Chapters & Milestones",
  subtitle: "Classic Timeline Exploration",
  objective: "Reflect on landmark life milestones in calm chronological sequence.",
  cognitive_family: "autobiographical_sequencing",
  difficulty: 1,
  modality: "photo_plus_voice",
  culture: "pan_indic",
  temporal_frame: "past",
  difficulty_config: {
    level: 1,
    choice_count: 2,
    initial_scaffolding: "independent",
    allow_drag_reordering: true,
    auto_cue_after_ms: 8000,
    retry_policy: "gentle_encouragement",
  },
  content_bindings: {
    milestones: [
      {
        id: "ms_school_days",
        title: "School Days & Learning",
        assamese_title: "বিদ্যালয়ৰ দিনবোৰ",
        approximate_year: "1956",
        era_label: "Youth",
        photo_url: "/assets/images/tezpur_school_memory_1789020475367.jpg",
        chronological_order: 1,
      },
      {
        id: "ms_teaching_career",
        title: "Teaching Literature",
        assamese_title: "সাহিত্য শিক্ষকতা",
        approximate_year: "1966",
        era_label: "Early Career",
        photo_url: "/assets/images/vintage_teacher_memory_1789020507713.jpg",
        chronological_order: 2,
      },
      {
        id: "ms_wedding_day",
        title: "Wedding Day & Home",
        assamese_title: "বিবাহৰ দিন",
        approximate_year: "1968",
        era_label: "Family Foundation",
        photo_url: "/assets/images/vintage_assamese_wedding_1789020439671.jpg",
        chronological_order: 3,
      },
    ],
    comparison_pair: {
      first_milestone_id: "ms_school_days",
      second_milestone_id: "ms_teaching_career",
      earlier_milestone_id: "ms_school_days",
      stimulus_prompt: "Which of these two times came earlier in your story?",
    },
  },
  scaffolding: {
    ladder: [
      "independent",
      "contextual_cue",
      "modality_shift",
      "narrowed_choice",
      "partial_reveal",
      "full_support",
    ],
    hint_available: true,
    contextual_text_cue: "Look at the students and books in the earlier classroom.",
    retry_policy: "gentle_encouragement",
  },
  instructions: {
    primary_prompt: "Which treasured memory came earlier?",
    spoken_prompt: "Look at these two moments. Which one happened earlier in your journey?",
    success_celebration: "Every memory shared today is treasured and placed with love.",
  },
  provenance_refs: ["provenance:system_verified_curated"],
  validation_status: {
    grounding_passed: true,
    consent_passed: true,
    safety_passed: true,
    dignity_passed: true,
    schema_passed: true,
    all_passed: true,
  },
  dignity_contract: {
    no_failure_states: true,
    no_visible_countdown: true,
    no_comparative_scoring: true,
    gentle_closure: true,
  },
};

// ── 2. Parametrically Personalised Spec (Level B) ────────────────────────────
export const personalisedPrepareForSpecLevelB: GameExperienceSpecification = {
  id: "spec_prepare_for_param_level_b",
  person_id: "person:purnima",
  template_key: "prepare_for",
  template_version: "1.2.0",
  version: "1.2.0",
  generation_mode: "parametrically_personalised_level_b",
  title: "Prepare-For: Afternoon Guest",
  subtitle: "Daily Hospitality Ritual",
  objective: "Engage executive step planning and prospective memory for today's afternoon visitor.",
  cognitive_family: "prospective_orientation",
  difficulty: 2,
  modality: "multi_modal",
  culture: "assamese_tezpur",
  temporal_frame: "future",
  difficulty_config: {
    level: 2,
    choice_count: 3,
    initial_scaffolding: "independent",
    allow_drag_reordering: true,
    auto_cue_after_ms: 10000,
    retry_policy: "gentle_encouragement",
  },
  content_bindings: {
    event: {
      id: "evt_afternoon_tea",
      title: "Afternoon Veranda Tea",
      scheduled_at: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
      formatted_time: "4:00 PM",
      location: "Front Veranda",
      visitor_name: "Granddaughter Rina",
      relationship: "Granddaughter",
      photo_url: "/assets/images/vintage_teacher_memory_1789020507713.jpg",
      phone_number: "+91 98640 12345",
    },
    visitor_choices: [
      {
        id: "vis_rina",
        name: "Granddaughter Rina",
        relationship: "Granddaughter (আদৰৰ নাতি)",
        photo_url: "/assets/images/vintage_teacher_memory_1789020507713.jpg",
        is_expected: true,
      },
      {
        id: "vis_bhaben",
        name: "Uncle Bhaben",
        relationship: "Neighbor (চুবুৰীয়া)",
        photo_url: "/assets/images/vintage_assamese_wedding_1789020439671.jpg",
        is_expected: false,
      },
    ],
    preparation_steps: [
      {
        id: "step_boil",
        step_number: 1,
        label: "Boil clean spring water in the kettle",
        detail: "Start with fresh water on the stove",
      },
      {
        id: "step_leaves",
        step_number: 2,
        label: "Add fragrant Assam CTC tea leaves",
        detail: "A teaspoon of golden BOP tea leaves",
      },
      {
        id: "step_spice",
        step_number: 3,
        label: "Crush fresh ginger and green cardamom",
        detail: "Warm comforting aroma",
      },
      {
        id: "step_pour",
        step_number: 4,
        label: "Pour hot tea into traditional brass cups",
        detail: "Serve with warm rice pitha",
      },
    ],
    preparation_items: [
      { id: "item_kettle", label: "Tea Kettle", category: "hospitality", icon: "🫖", is_relevant: true },
      { id: "item_leaves", label: "Assam Tea Leaves", category: "hospitality", icon: "🍃", is_relevant: true },
      { id: "item_cardamom", label: "Cardamom Pod", category: "hospitality", icon: "🌱", is_relevant: true },
      { id: "item_cups", label: "Brass Cups (Ban-Bhati)", category: "ritual", icon: "☕", is_relevant: true },
      { id: "item_umbrella", label: "Walking Umbrella", category: "personal", icon: "☂️", is_relevant: false },
    ],
  },
  scaffolding: {
    ladder: [
      "independent",
      "contextual_cue",
      "modality_shift",
      "narrowed_choice",
      "partial_reveal",
      "full_support",
    ],
    hint_available: true,
    family_voice_prompt: {
      speaker_name: "Rina",
      relationship: "Granddaughter",
      text: "Aitâ, I will arrive at 4:00 PM. Let us enjoy tea on the veranda together.",
      audio_url: "/assets/audio/rina_voice_sample.mp3",
    },
    contextual_text_cue: "Rina loves fresh cardamom in her tea.",
    retry_policy: "gentle_encouragement",
  },
  instructions: {
    primary_prompt: "Who is visiting you this afternoon?",
    spoken_prompt: "Who is coming over for tea at four o'clock today?",
    success_celebration: "Everything is beautifully prepared. Your home is warm and ready.",
  },
  provenance_refs: ["caregiver_note_001", "family_calendar_002"],
  validation_status: {
    grounding_passed: true,
    consent_passed: true,
    safety_passed: true,
    dignity_passed: true,
    schema_passed: true,
    all_passed: true,
  },
  dignity_contract: {
    no_failure_states: true,
    no_visible_countdown: true,
    no_comparative_scoring: true,
    gentle_closure: true,
  },
};

// ── 3. Dynamically Composed Spec (Level C) ───────────────────────────────────
export const dynamicComposedTimelineSpecLevelC: GameExperienceSpecification = {
  id: "spec_dynamic_composed_level_c",
  person_id: "person:purnima",
  template_key: "my_life_timeline",
  template_version: "1.2.0",
  version: "1.2.0",
  generation_mode: "dynamically_composed_level_c",
  title: "Dynamic Autobiographical Braid",
  subtitle: "Synthesized from Authentic Family Archives",
  objective: "Interleave autobiographical photo recognition with emotional resonance and era anchoring.",
  cognitive_family: "autobiographical_sequencing",
  difficulty: 2,
  modality: "photo_plus_voice",
  culture: "assamese_tezpur",
  temporal_frame: "past",
  difficulty_config: {
    level: 2,
    choice_count: 2,
    initial_scaffolding: "independent",
    allow_drag_reordering: true,
    auto_cue_after_ms: 9000,
    retry_policy: "gentle_encouragement",
  },
  content_bindings: {
    milestones: [
      {
        id: "ms_dyn_1",
        title: "Tezpur Girls High School",
        approximate_year: "1956",
        era_label: "Student Days",
        photo_url: "/assets/images/tezpur_school_memory_1789020475367.jpg",
        chronological_order: 1,
      },
      {
        id: "ms_dyn_2",
        title: "Teaching Bengali & Assamese Literature",
        approximate_year: "1966",
        era_label: "First Teaching Post",
        photo_url: "/assets/images/vintage_teacher_memory_1789020507713.jpg",
        chronological_order: 2,
      },
      {
        id: "ms_dyn_3",
        title: "Wedding at Tezpur Ancestral Courtyard",
        approximate_year: "1968",
        era_label: "Wedding Day",
        photo_url: "/assets/images/vintage_assamese_wedding_1789020439671.jpg",
        chronological_order: 3,
      },
    ],
    comparison_pair: {
      first_milestone_id: "ms_dyn_2",
      second_milestone_id: "ms_dyn_3",
      earlier_milestone_id: "ms_dyn_2",
      stimulus_prompt: "Which took place first: teaching literature or wedding day in Tezpur?",
    },
  },
  scaffolding: {
    ladder: [
      "independent",
      "contextual_cue",
      "modality_shift",
      "narrowed_choice",
      "partial_reveal",
      "full_support",
    ],
    hint_available: true,
    family_voice_prompt: {
      speaker_name: "Daughter Anu",
      relationship: "Daughter",
      text: "Ma, remember when you started teaching at the Girls School right before your wedding?",
      audio_url: "/assets/audio/anu_voice_sample.mp3",
    },
    contextual_text_cue: "Teaching began two years before the wedding celebration in 1968.",
    retry_policy: "gentle_encouragement",
  },
  instructions: {
    primary_prompt: "Which milestone came earlier in your story?",
    spoken_prompt: "Think about your teaching days and wedding day. Which came first?",
    success_celebration: "What a beautiful and enduring life story you have woven.",
  },
  provenance_refs: ["mem_001_caregiver_verified", "mem_002_family_verified"],
  validation_status: {
    grounding_passed: true,
    consent_passed: true,
    safety_passed: true,
    dignity_passed: true,
    schema_passed: true,
    all_passed: true,
  },
  dignity_contract: {
    no_failure_states: true,
    no_visible_countdown: true,
    no_comparative_scoring: true,
    gentle_closure: true,
  },
};
