/**
 * Typed GameExperienceSpecification
 *
 * Reusable, deterministic game generation and runtime schema for:
 * - Game 7: Reminiscence Journey (My World)
 * - Game 8: Route Builder (Familiar Places)
 *
 * Enforces strict typing. The LLM may generate only structured JSON conforming to this schema.
 * Executable code is never generated by the LLM.
 */

import {
  TemporalFrame,
  MemoryVerificationStatus,
  MemorySource,
  ConsentScope,
  VisibilityScope,
  SensitivityLevel,
} from "../../domain/cognitive-experience";

export type GameTemplate =
  | "reminiscence_journey_my_world"
  | "route_builder_familiar_places";

export type ReminiscenceScaffoldingLevel =
  | "recognition"
  | "cued_recognition"
  | "reduced_cue"
  | "multimodal_cue"
  | "recall_reminiscence";

export type RouteScaffoldingLevel =
  | "destination_recognition"
  | "obvious_route"
  | "landmark_sequencing"
  | "reduced_visual_cues"
  | "independent_route_recall";

export type ScaffoldingLevel = ReminiscenceScaffoldingLevel | RouteScaffoldingLevel;

export type GameModality =
  | "photo_plus_voice"
  | "visual_tactile"
  | "multimodal"
  | "audio_guided";

export type DifficultyLevel = 1 | 2 | 3;

export interface ProvenanceReference {
  entity_id: string;
  entity_type: "memory" | "place" | "route" | "media" | "voice_note" | "landmark";
  source: MemorySource;
  verification_status: MemoryVerificationStatus;
  verified_by: string;
  confidence: number;
  consent_scope: ConsentScope;
  visibility_scope: VisibilityScope;
  sensitivity: SensitivityLevel;
}

export interface MemoryPlaceBindings {
  person_id: string;
  memory_ids?: string[];
  place_ids?: string[];
  route_id?: string;
  destination_place_id?: string;
  landmark_ids?: string[];
  people_refs?: Array<{
    id: string;
    name: string;
    relationship: string;
    verified: boolean;
  }>;
  cultural_anchors?: string[];
  ambient_soundscapes?: string[];
}

export interface StepStimulus {
  image_url?: string;
  image_caption?: string;
  alt_text?: string;
  audio_url?: string;
  ambient_sound?: "courtyard" | "flute" | "tanpura" | "river" | "market" | string;
  sensory_description?: string;
  sensory_anchors?: Array<{
    icon: string;
    label: string;
    soundType?: string;
  }>;
  landmark_cue?: string;
  family_voice_note?: {
    speaker_name: string;
    relationship: string;
    transcript: string;
    assamese_transcript?: string;
    audio_url?: string;
  };
}

export interface StepPrompt {
  primary_prompt: string;
  assamese_prompt?: string;
  spoken_prompt?: string;
  guidance_cue?: string;
}

export interface ResponseOption {
  id: string;
  text: string;
  assamese_text?: string;
  image_url?: string;
  is_preferred_or_target: boolean;
  gentle_affirmation: string;
  subtle_visual_cue?: string;
}

export interface AllowedResponses {
  input_mode: "single_tap" | "multi_tap_sequence" | "voice_response" | "free_explore";
  options?: ResponseOption[];
  target_sequence_ids?: string[];
  allow_voice: boolean;
  min_options_count?: number;
  max_options_count?: number;
}

export interface StepHints {
  level_1_gentle_reminder: string;
  level_2_visual_cue?: string;
  level_3_family_voice?: {
    speaker: string;
    relationship: string;
    text: string;
    audio_url?: string;
  };
}

export interface StepFeedback {
  affirmation: string;
  assamese_affirmation?: string;
  gentle_retry_prompt: string;
  no_wrong_answers_note?: string;
}

export interface StepSpecification {
  step_id: string;
  step_index: number;
  title: string;
  assamese_title?: string;
  stop_type?:
    | "person"
    | "family"
    | "place"
    | "childhood"
    | "school"
    | "work"
    | "music"
    | "important_life_moment"
    | "family_story";
  step_type: ScaffoldingLevel | "voice_reflection";
  stimulus: StepStimulus;
  prompt: StepPrompt;
  allowed_responses: AllowedResponses;
  hints: StepHints;
  feedback: StepFeedback;
}

export interface ScaffoldingConfiguration {
  current_level: ScaffoldingLevel;
  scaffolding_hierarchy: ScaffoldingLevel[];
  auto_scaffold_on_pause: boolean;
  family_voice_available: boolean;
  visual_cue_level: "full" | "subtle" | "hidden_until_hint";
  guidance_tolerance: "high" | "moderate" | "minimal";
}

export interface SafetyConstraints {
  no_failure_screen: boolean;
  no_harsh_wrong_language: boolean;
  no_competitive_scoring: boolean;
  no_countdown_timers: boolean;
  graceful_exit_always_available: boolean;
  skip_allowed_without_penalty: boolean;
  pause_allowed: boolean;
  max_trials_per_session: number;
}

export interface AccessibilityConfiguration {
  minimum_touch_target_px: number;
  high_contrast_support: boolean;
  font_size_scale: "normal" | "large" | "extra_large";
  screen_reader_labels: boolean;
  bilingual_dual_display: boolean;
  haptic_or_visual_pulse: boolean;
}

export interface CompletionConfiguration {
  celebration_title: string;
  celebration_message: string;
  assamese_celebration_message?: string;
  summary_reminiscence_prompt: string;
  graceful_exit_text: string;
}

export interface ValidationDetail {
  validator_name: string;
  passed: boolean;
  errors: string[];
  warnings: string[];
  details?: Record<string, any>;
}

export interface ValidationSummary {
  is_valid: boolean;
  validated_at: string;
  validators: Record<string, ValidationDetail>;
  rejection_reasons: string[];
}

export interface GameExperienceSpecification {
  spec_id: string;
  person_id: string;
  version: string;
  created_at: string;
  game_template: GameTemplate;
  objective: string;
  memory_place_bindings: MemoryPlaceBindings;
  sequence: StepSpecification[];
  prompt: {
    session_title: string;
    session_subtitle: string;
    assamese_title?: string;
    welcome_prompt: string;
    assamese_welcome_prompt?: string;
  };
  modality: GameModality;
  difficulty: DifficultyLevel;
  scaffolding: ScaffoldingConfiguration;
  allowed_responses_summary: string;
  hints_summary: string;
  feedback_policy: string;
  completion: CompletionConfiguration;
  provenance_references: ProvenanceReference[];
  safety_constraints: SafetyConstraints;
  accessibility_configuration: AccessibilityConfiguration;
  validation_result?: ValidationSummary;
}
